### ISSUE TITLE
conda gcc 4.8.5 installation problem 

### ISSUE THREAD

**Issue by hmassalha** [mpicbg-csbd/stardist#122]
Hi , 

I installed the conda gcc from `conda install -c conda-forge/label/cf201901 gcc `
running the command `gcc --version` will give:

```
gcc (GCC) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

````

I still getting in error `ERROR: Could not build wheels for stardist which use PEP 517 and cannot be installed directly` when installing stardist. Which as I understand is related to not able to generate the gcc wheels... any suggestions how to come over this if I can't use Homebrew installation? 

Thanks a lot, HM

**Comment by maweigert** [comment]
Hi @hmassalha ,

How exactly did you install stardist and what is the full output?

Cheers,
M

**Comment by hmassalha** [comment]
Hi, 
thanks for your reply. I installed stardist with `pip install stardist` command. The output is the following:

```
(hm) mib115076i:~ hm11$ pip install stardist
Collecting stardist
  Using cached stardist-0.6.1.tar.gz (410 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numba in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from stardist) (0.52.0)
Requirement already satisfied: scikit-image in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from stardist) (0.17.2)
Requirement already satisfied: csbdeep>=0.6.0 in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from stardist) (0.6.1)
Requirement already satisfied: tifffile in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from csbdeep>=0.6.0->stardist) (2021.2.1)
Requirement already satisfied: keras<2.4,>=2.1.2 in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from csbdeep>=0.6.0->stardist) (2.3.1)
Requirement already satisfied: h5py<3 in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from csbdeep>=0.6.0->stardist) (2.10.0)
Requirement already satisfied: scipy in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from csbdeep>=0.6.0->stardist) (1.6.1)
Requirement already satisfied: matplotlib in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from csbdeep>=0.6.0->stardist) (3.3.4)
Requirement already satisfied: six in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from csbdeep>=0.6.0->stardist) (1.15.0)
Requirement already satisfied: numpy in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from csbdeep>=0.6.0->stardist) (1.20.1)
Requirement already satisfied: tqdm in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from csbdeep>=0.6.0->stardist) (4.58.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from keras<2.4,>=2.1.2->csbdeep>=0.6.0->stardist) (1.1.2)
Requirement already satisfied: pyyaml in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from keras<2.4,>=2.1.2->csbdeep>=0.6.0->stardist) (5.4.1)
Requirement already satisfied: keras-applications>=1.0.6 in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from keras<2.4,>=2.1.2->csbdeep>=0.6.0->stardist) (1.0.8)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from matplotlib->csbdeep>=0.6.0->stardist) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from matplotlib->csbdeep>=0.6.0->stardist) (2.8.1)
Requirement already satisfied: cycler>=0.10 in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from matplotlib->csbdeep>=0.6.0->stardist) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from matplotlib->csbdeep>=0.6.0->stardist) (8.1.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from matplotlib->csbdeep>=0.6.0->stardist) (1.3.1)
Requirement already satisfied: setuptools in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from numba->stardist) (53.1.0)
Requirement already satisfied: llvmlite<0.36,>=0.35.0 in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from numba->stardist) (0.35.0)
Requirement already satisfied: networkx>=2.0 in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from scikit-image->stardist) (2.5)
Requirement already satisfied: imageio>=2.3.0 in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from scikit-image->stardist) (2.9.0)
Requirement already satisfied: PyWavelets>=1.1.1 in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from scikit-image->stardist) (1.1.1)
Requirement already satisfied: decorator>=4.3.0 in ./opt/miniconda3/envs/hm/lib/python3.8/site-packages (from networkx>=2.0->scikit-image->stardist) (4.4.2)
Building wheels for collected packages: stardist
  Building wheel for stardist (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/hm11/opt/miniconda3/envs/hm/bin/python /Users/hm11/opt/miniconda3/envs/hm/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/hq/0g1939tj4j9bc5q66w8ry204000ly3/T/tmphvx3mlm2
       cwd: /private/var/folders/hq/0g1939tj4j9bc5q66w8ry204000ly3/T/pip-install-xjn4wkp0/stardist_6bfd08bf18bc45738a7f431ce43546ec
  Complete output (106 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/stardist
  copying stardist/version.py -> build/lib.macosx-10.9-x86_64-3.8/stardist
  copying stardist/rays3d.py -> build/lib.macosx-10.9-x86_64-3.8/stardist
  copying stardist/sample_patches.py -> build/lib.macosx-10.9-x86_64-3.8/stardist
  copying stardist/nms.py -> build/lib.macosx-10.9-x86_64-3.8/stardist
  copying stardist/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/stardist
  copying stardist/matching.py -> build/lib.macosx-10.9-x86_64-3.8/stardist
  copying stardist/utils.py -> build/lib.macosx-10.9-x86_64-3.8/stardist
  copying stardist/big.py -> build/lib.macosx-10.9-x86_64-3.8/stardist
  creating build/lib.macosx-10.9-x86_64-3.8/stardist/plot
  copying stardist/plot/plot.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/plot
  copying stardist/plot/render.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/plot
  copying stardist/plot/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/plot
  creating build/lib.macosx-10.9-x86_64-3.8/stardist/models
  copying stardist/models/model3d.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/models
  copying stardist/models/model2d.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/models
  copying stardist/models/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/models
  copying stardist/models/base.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/models
  creating build/lib.macosx-10.9-x86_64-3.8/stardist/geometry
  copying stardist/geometry/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/geometry
  copying stardist/geometry/geom3d.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/geometry
  copying stardist/geometry/geom2d.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/geometry
  creating build/lib.macosx-10.9-x86_64-3.8/stardist/kernels
  copying stardist/kernels/stardist2d.cl -> build/lib.macosx-10.9-x86_64-3.8/stardist/kernels
  copying stardist/kernels/stardist3d.cl -> build/lib.macosx-10.9-x86_64-3.8/stardist/kernels
  running build_ext
  building 'stardist.lib.stardist2d' extension
  Warning: Can't read registry to find the necessary compiler setting
  Make sure that Python modules winreg, win32api or win32con are installed.
  C compiler: gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/hm11/opt/miniconda3/envs/hm/include -arch x86_64 -I/Users/hm11/opt/miniconda3/envs/hm/include -arch x86_64
  
  creating build/temp.macosx-10.9-x86_64-3.8
  creating build/temp.macosx-10.9-x86_64-3.8/stardist
  creating build/temp.macosx-10.9-x86_64-3.8/stardist/lib
  compile options: '-I/private/var/folders/hq/0g1939tj4j9bc5q66w8ry204000ly3/T/pip-build-env-33kka7jk/overlay/lib/python3.8/site-packages/numpy/core/include -I/Users/hm11/opt/miniconda3/envs/hm/include/python3.8 -c'
  extra options: '-std=c++11 -fopenmp'
  gcc: stardist/lib/clipper.cpp
  gcc: stardist/lib/stardist2d.cpp
  gcc: stardist/lib/utils.cpp
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  In file included from stardist/lib/utils.cpp:1:0:
  stardist/lib/utils.h:4:19: fatal error: stdio.h: No such file or directory
   #include <stdio.h>
                     ^
  compilation terminated.
  In file included from /Users/hm11/opt/miniconda3/envs/hm/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/syslimits.h:7:0,
                   from /Users/hm11/opt/miniconda3/envs/hm/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:34,
                   from /Users/hm11/opt/miniconda3/envs/hm/include/python3.8/Python.h:11,
                   from stardist/lib/stardist2d.cpp:1:
  /Users/hm11/opt/miniconda3/envs/hm/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
   #include_next <limits.h>  /* recurse down to the real one */
                                                               ^
  compilation terminated.
  In file included from /Users/hm11/opt/miniconda3/envs/hm/gcc/include/c++/bits/postypes.h:40:0,
                   from /Users/hm11/opt/miniconda3/envs/hm/gcc/include/c++/bits/char_traits.h:40,
                   from /Users/hm11/opt/miniconda3/envs/hm/gcc/include/c++/string:40,
                   from /Users/hm11/opt/miniconda3/envs/hm/gcc/include/c++/stdexcept:39,
                   from stardist/lib/clipper.hpp:55,
                   from stardist/lib/clipper.cpp:41:
  /Users/hm11/opt/miniconda3/envs/hm/gcc/include/c++/cwchar:44:19: fatal error: wchar.h: No such file or directory
   #include <wchar.h>
                     ^
  compilation terminated.
  compiling with OpenMP support failed, re-trying without
  building 'stardist.lib.stardist2d' extension
  C compiler: gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/hm11/opt/miniconda3/envs/hm/include -arch x86_64 -I/Users/hm11/opt/miniconda3/envs/hm/include -arch x86_64
  
  compile options: '-I/private/var/folders/hq/0g1939tj4j9bc5q66w8ry204000ly3/T/pip-build-env-33kka7jk/overlay/lib/python3.8/site-packages/numpy/core/include -I/Users/hm11/opt/miniconda3/envs/hm/include/python3.8 -c'
  extra options: '-std=c++11'
  gcc: stardist/lib/stardist2d.cpp
  gcc: stardist/lib/clipper.cpp
  gcc: stardist/lib/utils.cpp
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  In file included from stardist/lib/utils.cpp:1:0:
  stardist/lib/utils.h:4:19: fatal error: stdio.h: No such file or directory
   #include <stdio.h>
                     ^
  compilation terminated.
  In file included from /Users/hm11/opt/miniconda3/envs/hm/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/syslimits.h:7:0,
                   from /Users/hm11/opt/miniconda3/envs/hm/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:34,
                   from /Users/hm11/opt/miniconda3/envs/hm/include/python3.8/Python.h:11,
                   from stardist/lib/stardist2d.cpp:1:
  /Users/hm11/opt/miniconda3/envs/hm/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
   #include_next <limits.h>  /* recurse down to the real one */
                                                               ^
  compilation terminated.
  In file included from /Users/hm11/opt/miniconda3/envs/hm/gcc/include/c++/bits/postypes.h:40:0,
                   from /Users/hm11/opt/miniconda3/envs/hm/gcc/include/c++/bits/char_traits.h:40,
                   from /Users/hm11/opt/miniconda3/envs/hm/gcc/include/c++/string:40,
                   from /Users/hm11/opt/miniconda3/envs/hm/gcc/include/c++/stdexcept:39,
                   from stardist/lib/clipper.hpp:55,
                   from stardist/lib/clipper.cpp:41:
  /Users/hm11/opt/miniconda3/envs/hm/gcc/include/c++/cwchar:44:19: fatal error: wchar.h: No such file or directory
   #include <wchar.h>
                     ^
  compilation terminated.
  error: Command "gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/hm11/opt/miniconda3/envs/hm/include -arch x86_64 -I/Users/hm11/opt/miniconda3/envs/hm/include -arch x86_64 -I/private/var/folders/hq/0g1939tj4j9bc5q66w8ry204000ly3/T/pip-build-env-33kka7jk/overlay/lib/python3.8/site-packages/numpy/core/include -I/Users/hm11/opt/miniconda3/envs/hm/include/python3.8 -c stardist/lib/utils.cpp -o build/temp.macosx-10.9-x86_64-3.8/stardist/lib/utils.o -std=c++11" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for stardist
Failed to build stardist
ERROR: Could not build wheels for stardist which use PEP 517 and cannot be installed directly
```

Thanks, HM

**Comment by uschmidt83** [comment]
I'm not sure, but gcc 4.8.5 could be too old. Please try with a more recent one. (We recommend to install gcc via homebrew.)

**Comment by maweigert** [comment]
>  stardist/lib/utils.h:4:19: fatal error: stdio.h: No such file or directory

Seems like the conda install of gcc didn't provide even the most basic header files (I remember seeing this elsewhere). Is there a specific reason why you cannot install gcc via homebrew (`brew install gcc`)?

**Comment by hmassalha** [comment]
I managed to install `gcc` from `brew`, and then managed to install `stardist` using the following command `CC=gcc-10 CXX=g++-10 pip install stardist`

however, when importing `stardist` using `import stardist` I got the following error:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-68ba725596b5> in <module>
----> 1 import stardist

~/opt/miniconda3/envs/hm/lib/python3.8/site-packages/stardist/__init__.py in <module>
      6 from .nms import non_maximum_suppression, non_maximum_suppression_3d, non_maximum_suppression_3d_sparse
      7 from .utils import edt_prob, fill_label_holes, sample_points, calculate_extents, export_imagej_rois, gputools_available
----> 8 from .geometry import star_dist,   polygons_to_label,   relabel_image_stardist, ray_angles, dist_to_coord
      9 from .geometry import star_dist3D, polyhedron_to_label, relabel_image_stardist3D
     10 from .plot.plot import random_label_cmap, draw_polygons, _draw_polygons

~/opt/miniconda3/envs/hm/lib/python3.8/site-packages/stardist/geometry/__init__.py in <module>
      3 # TODO: rethink naming for 2D/3D functions
      4 
----> 5 from .geom2d import star_dist, polygons_to_label, relabel_image_stardist, ray_angles, dist_to_coord
      6 from .geom3d import star_dist3D, polyhedron_to_label, relabel_image_stardist3D, dist_to_coord3D, export_to_obj_file3D
      7 

~/opt/miniconda3/envs/hm/lib/python3.8/site-packages/stardist/geometry/geom2d.py in <module>
      9 from ..utils import path_absolute, _is_power_of_2, _normalize_grid
     10 from ..matching import _check_label_array
---> 11 from ..lib.stardist2d import c_star_dist
     12 
     13 

ImportError: dlopen(/Users/hm11/opt/miniconda3/envs/hm/lib/python3.8/site-packages/stardist/lib/stardist2d.cpython-38-darwin.so, 2): Symbol not found: __ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEmmPKcm
  Referenced from: /Users/hm11/opt/miniconda3/envs/hm/lib/python3.8/site-packages/stardist/lib/stardist2d.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/hm11/opt/miniconda3/envs/hm/lib/python3.8/site-packages/stardist/lib/stardist2d.cpython-38-darwin.so
```

if I understand it correctly, this error message is looking for `stardist2d` package which is different from [https://github.com/mpicbg-csbd/stardist/issues/19#issuecomment-535610758](url). Any suggestions?

Thanks, HM

**Comment by hmassalha** [comment]
Hi, 

I followed the steps from [https://github.com/mpicbg-csbd/stardist/issues/19#issuecomment-535610758](url) and got the following error:

```
(hm) mib115076i:~ hm11$ python -c "import stardist"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/hm11/opt/miniconda3/envs/hm/lib/python3.8/site-packages/stardist/__init__.py", line 8, in <module>
    from .geometry import star_dist,   polygons_to_label,   relabel_image_stardist, ray_angles, dist_to_coord
  File "/Users/hm11/opt/miniconda3/envs/hm/lib/python3.8/site-packages/stardist/geometry/__init__.py", line 5, in <module>
    from .geom2d import star_dist, polygons_to_label, relabel_image_stardist, ray_angles, dist_to_coord
  File "/Users/hm11/opt/miniconda3/envs/hm/lib/python3.8/site-packages/stardist/geometry/geom2d.py", line 11, in <module>
    from ..lib.stardist2d import c_star_dist
ImportError: dlopen(/Users/hm11/opt/miniconda3/envs/hm/lib/python3.8/site-packages/stardist/lib/stardist2d.cpython-38-darwin.so, 2): Library not loaded: gcc/10.2.0_4/lib/gcc/10/libgomp.1.dylib
  Referenced from: /Users/hm11/opt/miniconda3/envs/hm/lib/python3.8/site-packages/stardist/lib/stardist2d.cpython-38-darwin.so
  Reason: image not found
```

which is similar to [https://github.com/mpicbg-csbd/stardist/issues/49#issuecomment-627664477](url).. Any suggestions? 

I can add that I installed `brew` locally as explained in [https://www.scivision.dev/macos-homebrew-non-sudo/](url), and added the path to $PATH, I have now gcc-10. 

Thanks for your help, 
HM

**Comment by hmassalha** [comment]
Working for me! 

1.I installed `brew` from not `sudo` user.
2. Thanks to [https://github.com/mpicbg-csbd/stardist/issues/56#issuecomment-629637000](https://github.com/mpicbg-csbd/stardist/issues/56#issuecomment-629637000) I followed his notes for updating the path for `libstdc++.6.dylib`, `libgomp.1.dylib` and `libgcc_s.1.dylib`

working for me, Many thanks,

**Comment by maweigert** [comment]
Glad that it worked! :)
