### ISSUE TITLE
Problems loading new model in Fiji

### ISSUE THREAD

**Issue by tboo** [mpicbg-csbd/stardist#42]
Hi all -

Just had a first climpse at StarDist 2D and it's performance is outstanding. Really happy with it :)

While I managed to train and use a 2D model for prediction (using the jupyther notebooks), I am struggling to load the model with the Fiji plugin. The generic models that ship with the plugin work without problems.

I simply zipped the content of the respective model folder I generated with the notebooks and tried to load it. An error as follows was returned:

```
[INFO] Using default TensorFlow version from JAR: TF 1.12.0 CPU
[INFO] Loading TensorFlow model GenericNetwork_f1776fcd341bf3d6cbb63ac2c6fff03c from source file file:/scratch/models/Markus_ScanR_stardist/stardist_scanR.zip
[INFO] Unpacking config.json
[INFO] Unpacking events.out.tfevents.1585666494.ffbc03565224
[INFO] Unpacking thresholds.json
[INFO] Unpacking weights_best.h5
[INFO] Unpacking weights_last.h5
org.tensorflow.TensorFlowException: Could not find SavedModel .pb or .pbtxt at supplied export directory path: /home/tboothe/Fiji.app/models/GenericNetwork_f1776fcd341bf3d6cbb63ac2c6fff03c
	at org.tensorflow.SavedModelBundle.load(Native Method)
	at org.tensorflow.SavedModelBundle.access$000(SavedModelBundle.java:27)
	at org.tensorflow.SavedModelBundle$Loader.load(SavedModelBundle.java:32)
	at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:95)
	at net.imagej.tensorflow.CachedModelBundle.<init>(CachedModelBundle.java:44)
	at net.imagej.tensorflow.DefaultTensorFlowService.loadCachedModel(DefaultTensorFlowService.java:135)
	at de.csbdresden.csbdeep.network.model.tensorflow.TensorFlowNetwork.loadModel(TensorFlowNetwork.java:135)
	at de.csbdresden.csbdeep.network.model.DefaultNetwork.loadModel(DefaultNetwork.java:48)
	at de.csbdresden.csbdeep.network.DefaultModelLoader.loadNetwork(DefaultModelLoader.java:41)
	at de.csbdresden.csbdeep.network.DefaultModelLoader.run(DefaultModelLoader.java:20)
	at de.csbdresden.csbdeep.commands.GenericCoreNetwork.tryToPrepareInputAndNetwork(GenericCoreNetwork.java:523)
	at de.csbdresden.csbdeep.commands.GenericCoreNetwork.initiateModelIfNeeded(GenericCoreNetwork.java:303)
	at de.csbdresden.csbdeep.commands.GenericCoreNetwork.mainThread(GenericCoreNetwork.java:445)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at de.csbdresden.csbdeep.network.DefaultInputValidator.checkForTooManyDimensions(DefaultInputValidator.java:32)
	at de.csbdresden.csbdeep.network.DefaultInputValidator.run(DefaultInputValidator.java:18)
	at de.csbdresden.csbdeep.commands.GenericCoreNetwork.tryToPrepareInputAndNetwork(GenericCoreNetwork.java:526)
	at de.csbdresden.csbdeep.commands.GenericCoreNetwork.initiateModelIfNeeded(GenericCoreNetwork.java:303)
	at de.csbdresden.csbdeep.commands.GenericCoreNetwork.mainThread(GenericCoreNetwork.java:445)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] CSBDeep plugin exit (took 3643 milliseconds)
[ERROR] Module threw exception
java.lang.NullPointerException
	at de.csbdresden.stardist.StarDist2D.splitPrediction(StarDist2D.java:320)
	at de.csbdresden.stardist.StarDist2D.run(StarDist2D.java:292)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Am I reading this correctly, that Fiji still tries to load the generic model despite the fact that I am specifying the zip file of my own model?

Thanks a lot in advance for some feedback on that matter.

**Comment by maweigert** [comment]
Hi @tboo,

> Just had a first climpse at StarDist 2D and it's performance is outstanding. Really happy with it :)

Glad you like it! :)

> I simply zipped the respective model folder I generated with the notebooks

You need to call `model.export_TF()`, which will create a file `TF_SavedModel.zip` in the respective model directory. You then have to point the Fiji plugin to `TF_SavedModel.zip` (make sure that tensorflow version of the exporting code and of Fiji are the same).

Let us know if that works! 

Cheers,
Martin

**Comment by tboo** [comment]
Thanks, @maweigert  :) This does the trick. Works like a charm now. (P.S.: trained my model with TF 1.15 but this seems to work with TF 1.14 in Fiji - close enough ;))
