### ISSUE TITLE
Stardist prediction allocates full gpu

### ISSUE THREAD

**Issue by constantinpape** [mpicbg-csbd/stardist#44]
I have noticed that stardist prediction allocates all memory on the gpu.
As far as I understand, this is the default behaviour of tensorflow, but can be changed:
https://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory

What would be the best way to do this when using stardist?

(I think for our use case, where we only predict on image at a time, only a small fraction of the gpu memory is used + the task is cpu bound, so the gpu could be used for other tasks concurrently if we don't allocate all memory)

**Comment by constantinpape** [comment]
Related: I think that when stardist prediction finishes, it does not free the gpu memory directly, only after the python process finishes. This is an issue when trying to run something else on the gpu after stardist within the same python processes, see also https://github.com/hci-unihd/batchlib/issues/13.

**Comment by maweigert** [comment]
Hi, 

> I have noticed that stardist prediction allocates all memory on the gpu.

Yes, this is default tensorflow behaviour. You can change the allocated memory by putting the following 

```
from csbdeep.utils.tf import limit_gpu_memory  
limit_gpu_memory(0.5)
```
at the start of a script (before model is loaded) and only the specific relative fraction of the GPU memory (e.g. 50% in the case above) should be used. 


> Related: I think that when stardist prediction finishes, it does not free the gpu memory directly, only after the python process finishes.

Yes, keras/tensorflow does not release memory easily, even after the session is closed. This appears to be a common issue of annoyance. According to [this thread](https://www.kaggle.com/c/jigsaw-unintended-bias-in-toxicity-classification/discussion/96876) the memory can be freed with `numba`:
```
from numba import cuda 
cuda.select_device(0) 
cuda.close()  
```  
This indeed does works for me on Linux.

Hope this helps!

**Comment by constantinpape** [comment]
Thanks for the fast reply!
I think this should fix all our issues. I will give it a try soon.

**Comment by constantinpape** [comment]
Ok, I tried this now, but nothing really works.
1. `limit_gpu_memory` fails with the following traceback: 
```
Traceback (most recent call last):                                                                                                                                                                          
  File "/g/kreshuk/pape/Work/covid/batchlib/batchlib/workflow.py", line 99, in run_workflow                                                                                                                 
    state = job(folder, **run_kwargs)                                                                                                                                                                       
  File "/g/kreshuk/pape/Work/covid/batchlib/batchlib/base.py", line 210, in __call__                                                                                                                        
    self.run(input_files, output_files, **kwargs)                                                                                                                                                           
  File "/g/kreshuk/pape/Work/covid/batchlib/batchlib/segmentation/stardist_prediction.py", line 92, in run                                                                                                  
    self.predict_all(input_files, output_files, gpu_id, n_jobs)                                                                                                                                             
  File "/g/kreshuk/pape/Work/covid/batchlib/batchlib/segmentation/stardist_prediction.py", line 77, in predict_all                                                                                          
    limit_gpu_memory(.1)                                                                                                                                                                                    
  File "/home/pape/Work/software/conda/miniconda3/envs/antibodies-gpu/lib/python3.7/site-packages/csbdeep/utils/tf.py", line 45, in limit_gpu_memory                                                        
    if K.tensorflow_backend._SESSION is None:                                                                                                                                                               
AttributeError: module 'keras.backend.tensorflow_backend' has no attribute '_SESSION'                                                                                                                       
Traceback (most recent call last):                                                                                                                                                                          
  File "run_all_workflows.py", line 62, in <module>                                                                                                                                                         
    run_all_workflows()                                                                                                                                                                                     
  File "run_all_workflows.py", line 50, in run_all_workflows                                                                                                                                                
    name, rt = run_instance_analysis2(config)                                                                                                                                                               
  File "/g/kreshuk/pape/Work/covid/batchlib/antibodies/instance_analysis_workflow2.py", line 123, in run_instance_analysis2                                                                                 
    ignore_failed_outputs=config.ignore_failed_outputs)                                                                                                                                                     
  File "/g/kreshuk/pape/Work/covid/batchlib/batchlib/workflow.py", line 104, in run_workflow                                                                                                                
    raise e                                                                                                                                                                                                 
  File "/g/kreshuk/pape/Work/covid/batchlib/batchlib/workflow.py", line 99, in run_workflow                                                                                                                 
    state = job(folder, **run_kwargs)                                                                                                                                                                       
  File "/g/kreshuk/pape/Work/covid/batchlib/batchlib/base.py", line 210, in __call__                                                                                                                        
    self.run(input_files, output_files, **kwargs)                                                                                                                                                           
  File "/g/kreshuk/pape/Work/covid/batchlib/batchlib/segmentation/stardist_prediction.py", line 92, in run                                                                                                  
    self.predict_all(input_files, output_files, gpu_id, n_jobs)                                                                                                                                             
  File "/g/kreshuk/pape/Work/covid/batchlib/batchlib/segmentation/stardist_prediction.py", line 77, in predict_all                                                                                          
    limit_gpu_memory(.1)                                                                                                                                                                                    
  File "/home/pape/Work/software/conda/miniconda3/envs/antibodies-gpu/lib/python3.7/site-packages/csbdeep/utils/tf.py", line 45, in limit_gpu_memory                                                        
    if K.tensorflow_backend._SESSION is None:                                                                                                                                                               
AttributeError: module 'keras.backend.tensorflow_backend' has no attribute '_SESSION' 
```
I am using tensroflow 1.15 and keras 2.3.1.

**Comment by constantinpape** [comment]
2. Using numba frees the gpu, BUT leaves it in a state that is not valid and pytorch then fails with the following error:
```
RuntimeError: CUDA error: invalid argument                                                                                                                                                                  
Traceback (most recent call last):                                                                                                                                                                          
  File "run_all_workflows.py", line 62, in <module>                                                                                                                                                         
    run_all_workflows()                                                                                                                                                                                     
  File "run_all_workflows.py", line 50, in run_all_workflows                                                                                                                                                
    name, rt = run_instance_analysis2(config)                                                                                                                                                               
  File "/g/kreshuk/pape/Work/covid/batchlib/antibodies/instance_analysis_workflow2.py", line 123, in run_instance_analysis2                                                                                 
    ignore_failed_outputs=config.ignore_failed_outputs)                                                                                                                                                     
  File "/g/kreshuk/pape/Work/covid/batchlib/batchlib/workflow.py", line 104, in run_workflow                                                                                                                
    raise e                                                                                                                                                                                                 
  File "/g/kreshuk/pape/Work/covid/batchlib/batchlib/workflow.py", line 99, in run_workflow                                                                                                                 
    state = job(folder, **run_kwargs)                                                                                                                                                                       
  File "/g/kreshuk/pape/Work/covid/batchlib/batchlib/base.py", line 421, in __call__                                                                                                                        
    super().__call__(folder, **kwargs)                                                                                                                                                                      
  File "/g/kreshuk/pape/Work/covid/batchlib/batchlib/base.py", line 210, in __call__                                                                                                                        
    self.run(input_files, output_files, **kwargs)                                                                                                                                                           
  File "/g/kreshuk/pape/Work/covid/batchlib/batchlib/analysis/cell_level_analysis.py", line 116, in run                                                                                                     
    _save_all_stats(input_file, output_file)                                                                                                                                                                
  File "/g/kreshuk/pape/Work/covid/batchlib/batchlib/analysis/cell_level_analysis.py", line 101, in save_all_stats                                                                                          
    sample = self.load_sample(in_file, device=device)                                                                                                                                                       
  File "/g/kreshuk/pape/Work/covid/batchlib/batchlib/analysis/cell_level_analysis.py", line 52, in load_sample                                                                                              
    marker = torch.FloatTensor(marker.astype(np.float32)).to(device)                                                                                                                                        
RuntimeError: CUDA error: invalid argument
```
(If I run the same task without tensorflow being involved it runs through without any issues).

3. I also tried running in a sub-process as suggested e.g. [here](https://stackoverflow.com/questions/39758094/clearing-tensorflow-gpu-memory-after-model-execution), but it results in the same issue as with 2.

**Comment by uschmidt83** [comment]
> 1. `limit_gpu_memory` fails with the following traceback:

Yes, this doesn't work with Keras > 2.2.5, see https://github.com/CSBDeep/CSBDeep/issues/40.

I forgot about that... thanks for the reminder. We haven't fixed that yet (not sure if we can).

**Comment by uschmidt83** [comment]
Try if this works for you:
```python
def limit_gpu_memory(fraction, allow_growth=False):
    import tensorflow as tf
    from keras import backend as K
    config = tf.ConfigProto()
    if fraction is not None:
        config.gpu_options.per_process_gpu_memory_fraction = fraction
    config.gpu_options.allow_growth = bool(allow_growth)
    session = tf.Session(config=config)
    K.tensorflow_backend.set_session(session)
```

**Comment by constantinpape** [comment]
> Try if this works for you:

Yes, that works and also fixes the subsequent problem of running pytorch.
Thanks!

**Comment by constantinpape** [comment]
Also, from my point this issue could be closed, but it would maybe be nice to add something about this in the README.
