### ISSUE TITLE
Error with groovy script exporting ground truth from QuPath

### ISSUE THREAD

**Issue by asasama12** [mpicbg-csbd/stardist#63]
I've used QuPath to export ground truth labels successfully in the past using the script that is included in the documentation, but today it suddenly stopped working.  I get the following error on the line: 

```java
request = RegionRequest.createInstance(imageData.getServerPath(), downsample, fullimage_annotation.getROI())

"ERROR: Error at line 35: No such property: RegionRequest for class: Script1

ERROR: Script error
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
    at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
    at Script1.run(Script1.groovy:36)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:343)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:152)
    at qupath.lib.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:765)
    at qupath.lib.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:695)
    at qupath.lib.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:677)
    at qupath.lib.scripting.DefaultScriptEditor.access$400(DefaultScriptEditor.java:136)
    at qupath.lib.scripting.DefaultScriptEditor$ProjectTask.call(DefaultScriptEditor.java:1267)
    at qupath.lib.scripting.DefaultScriptEditor$ProjectTask.call(DefaultScriptEditor.java:1195)
    at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)"
```

Has anyone seen this before?  Has there been some update to Groovy or Qupath that I'm not aware of? This error occurs on both the 0.1.2 and 0.2.0 versions of QuPath for me.

**Comment by uschmidt83** [comment]
We don't have much practical experience with QuPath ourselves, hence it's better if you ask the question [at the forum](https://forum.image.sc) and tag your post with `stardist` and `qupath`.

Thanks,
Uwe

**Comment by asasama12** [comment]
I actually was able to fix the issue.  If anyone else runs into this simply add the line: 
import qupath.lib.regions.RegionRequest
under the 'manage imports' heading within the script and it worked for me.
