### ISSUE TITLE
Problem in training "No module named stardist.lib.stardist"

### ISSUE THREAD

**Issue by Amos6666** [mpicbg-csbd/stardist#9]
Hello,

While training, it occurs that "ImportError: No module named stardist.lib.stardist" in utils.py, line 74, from .lib.stardist import c_star_dist. 
The detail is:

Epoch 1/100
Traceback (most recent call last):
  File "/home/x000000/anaconda3/lib/python3.5/site-packages/keras/utils/data_utils.py", line 578, in get
    inputs = self.queue.get(block=True).get()
  File "/home/x000000/anaconda3/lib/python3.5/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/x000000/anaconda3/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/x000000/anaconda3/lib/python3.5/site-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/home/x000000/SYF/stardist/stardist/model.py", line 100, in __getitem__
    dist      = np.stack([star_dist(lbl,self.n_rays) for lbl in Y])
  File "/home/x000000/SYF/stardist/stardist/model.py", line 100, in <listcomp>
    dist      = np.stack([star_dist(lbl,self.n_rays) for lbl in Y])
  File "/home/x000000/SYF/stardist/stardist/utils.py", line 121, in star_dist
    return _cpp_star_dist(a,n_rays)
  File "/home/x000000/SYF/stardist/stardist/utils.py", line 74, in _cpp_star_dist
    from .lib.stardist import c_star_dist
ImportError: No module named 'stardist.lib.stardist'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_1.py", line 94, in <module>
    model.train(X_trn,Y_trn,validation_data=(X_val,Y_val))
  File "/home/x000000/SYF/stardist/stardist/model.py", line 420, in train
    callbacks=self.callbacks, verbose=1)
  File "/home/x000000/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/x000000/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 2194, in fit_generator
    generator_output = next(output_generator)
  File "/home/x000000/anaconda3/lib/python3.5/site-packages/keras/utils/data_utils.py", line 584, in get
    six.raise_from(StopIteration(e), e)
  File "<string>", line 3, in raise_from
StopIteration: No module named 'stardist.lib.stardist'

I also tried to import stardist.lib.stardist in the terminal, but it doesn't work either.

**Comment by uschmidt83** [comment]
Hi, sorry for the late reply.

It seems that StarDist wasn't properly installed, specifically the C++ extension hasn't been compiled.
Can you please try to re-install it and post any error that might occur?

```
pip3 uninstall -y stardist
pip3 install -v stardist
```

Best,
Uwe

**Comment by hijizhou** [comment]
Uwe's solution goes well, just a small note of my case in case it be useful to others:

My environment is Windows+PyCharm+Python3.7. After re-installation `stardist`, the problem in Jupyter is still there. However, those import commands in Python console do not bring any errors "No module named 'stardist.lib.stardist2d'". It turns out my Jupyter is using a different kernel. I did the following things to make it work:

```
python3 -m pip install ipykernel
python3 -m ipykernel install --user
jupyter notebook
```

**Comment by lanfz2000** [comment]
I also encounter this problem when importing the stardist.

Here is the information.
Traceback (most recent call last):
  File "/mnt/data2/lanfz/codes/stardist-master/train_stardist.py", line 15, in <module>
    from stardist.models.model2d import Config2D, StarDist2D, StarDistData2D
  File "/mnt/data2/lanfz/codes/stardist-master/stardist/__init__.py", line 15, in <module>
    from .geometry import star_dist,   polygons_to_label,   relabel_image_stardist, ray_angles, dist_to_coord
  File "/mnt/data2/lanfz/codes/stardist-master/stardist/geometry/__init__.py", line 5, in <module>
    from .geom2d import star_dist, relabel_image_stardist, ray_angles, dist_to_coord, polygons_to_label, polygons_to_label_coord
  File "/mnt/data2/lanfz/codes/stardist-master/stardist/geometry/geom2d.py", line 11, in <module>
    from ..lib.stardist2d import c_star_dist
ModuleNotFoundError: No module named 'stardist.lib.stardist2d'

I have tried the solution above like:
pip3 uninstall -y stardist
pip3 install -v stardist
But it didn't work.
